# Generated by Django 3.0.7 on 2020-08-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothing',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
