# Generated by Django 3.0.7 on 2020-08-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200808_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=True, max_length=2083),
        ),
    ]
